# Generated by Django 2.2.3 on 2019-09-10 07:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('modified_at', models.DateTimeField(default=datetime.datetime.now)),
                ('session_key', models.CharField(max_length=40)),
                ('viewed_object_id', models.PositiveIntegerField()),
                ('kind', models.CharField(blank=True, max_length=50)),
                ('viewed_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'unique_together': {('session_key', 'viewed_content_type', 'viewed_object_id')},
            },
        ),
        migrations.CreateModel(
            name='DailyViewSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('modified_at', models.DateTimeField(default=datetime.datetime.now)),
                ('views_on', models.DateField()),
                ('count', models.PositiveIntegerField()),
                ('viewed_object_id', models.PositiveIntegerField()),
                ('kind', models.CharField(blank=True, max_length=50)),
                ('viewed_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'unique_together': {('views_on', 'viewed_content_type', 'viewed_object_id')},
            },
        ),
    ]
